## Q1: Fun with arrays

**A.**  Create the array: 
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.


**B.** Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [ ]:
import numpy as np

A = np.array([[j + i*5+1  for i in range(3)] for j in range(5)])
print(A.shape)
print(f"A:\n{A}")
print(f"second and fourth rows:\n{A[[1,3]]}")

(5, 3)
A:
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
second and fourth rows:
[[ 2  7 12]
 [ 4  9 14]]


## Q4: Bootstraps

Boostrapping is a prominent statistical tecnique to estimate errors when you're stuck and don't know what else to o: https://erikjanvankesteren.nl/blog/2018-03-01-baron-bootstrap.html

Generate a 1D array (say from a Gaussian, but then add some outliers for fun). Compute the bootstrapped 95% confidence intervals for the mean of that array (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 

In [ ]:

def bootstrap_confidence_intervals(data, num_bootstrap_samples=5000, confidence_level=0.95):
    bootMeans = []
    for _ in range(num_bootstrap_samples):
        bootSample = np.random.choice(data, size= int(len(data)/10), replace=True)
        bootMeans.append(np.mean(bootSample))
        lowPerc = (1 - confidence_level) / 2 * 100
        upPerc = 100 - lowPerc
        lower_confidence_interval = np.percentile(bootMeans, lowPerc)
        upper_confidence_interval = np.percentile(bootMeans, upPerc)
    return lower_confidence_interval, upper_confidence_interval        

In [ ]:
mean = 100
std_dev = 10
numSamples = 1000
numOutliers = 50
data = np.random.normal(mean, std_dev, numSamples) #now it's gaussian

outliers = np.random.uniform(120, 150, numOutliers) #outliers as uniform ditribution added to the gaussian
data = np.concatenate([data, outliers])
lower_ci, upper_ci = bootstrap_confidence_intervals(data)

print("Bootstrapped 95% confidence intervals for the mean:")
print("Lower CI:", lower_ci)
print("Upper CI:", upper_ci)


Bootstrapped 95% confidence intervals for the mean:
Lower CI: 99.55744471863855
Upper CI: 104.18233184622282
